services:
  backend:
    build: back-end
    ports:
      - 8000:8000
    volumes:
      - ./back-end:/usr/src/app
  frontend:
    build: front-end
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/usr/src/app
